administrator/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('dashboard/',views.admin_dashboard,name='administrator_dashboard'),
    path('student/registration/', views.register_student,name = 'register_student'),
    path('student/<int:id>/profile/', views.student_profile,name='student_profile'),
    path('search/', views.search_student,name = 'search_student'),
    path('update/<int:id>',views.update_student, name='update_student'),
    path('delete/<int:id>',views.delete_student, name='delete_student'),
    path('payment/<int:id>/', views.make_payment, name='make_payment'),
    path('transaction/<int:id>', views.transaction_details, name='transaction_details'),
    path('receipt/<int:id>/',views.download_receipt, name='download_receipt'),
    path('statement/<int:id>/', views.download_statement, name='download_statement'),
    path('reports/',views.reports, name='reports'),   
    path('search fees structure', views.search_fees_structure, name='search_fees_structure'),
    path('update/fees structure/<int:id>',views.update_fees_structure,name='update_fees_structure'),
    path('generate/school fees structure report',views.generate_fees_structure_report, name='generate_fees_structure_report'),
    path('generate/fees arrears report',views.generate_fees_arrears_report, name='generate_fees_arrears_report'),
    path('gennerate/lunch subscribers report',views.generate_lunch_subscribers_report, name='generate_lunch_subscribers_report'),
    path('generate/transport subscribers report',views.generate_transport_subscribers_report,name='generate_transport_subscribers_report'),

]

sims/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('account/',include('user_account.urls')),
    path('administrator/',include('administrator.urls')),
    path('student/',include('student.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administrator/models.py
from django.db import models
from user_account.models import CustomUser

class Administrator(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE,primary_key=True)
    

financial_account/models.py
from django.db import models
from student.models import Student

class FinancialAccount(models.Model):
    class Meta:
        ordering = ['-date_of_payment']

    """a financial account constitutes of financial transactions"""
    def __str__(self):
        return self.student.__str__()
    
    TRANSACTION_TYPE_CHOICES = (
        ('credit','Credit'),
        ('debit','Debit')
    )
    transaction_type = models.CharField(max_length=7,choices=TRANSACTION_TYPE_CHOICES,default='credit')
    date_of_payment = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=8,decimal_places=2)
    arrears = models.DecimalField(max_digits=8,decimal_places=2)
    student = models.ForeignKey(Student,on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        """This method will update the StudentFees table"""
        curr_bal = CurrentBalance.objects.filter(student=self.student).exists()# Check whether the specified record exists
        if curr_bal:
            curr_bal_record = CurrentBalance.objects.get(student=self.student)
            curr_bal_record.current_balance = self.arrears
            curr_bal_record.save()
        else:
            curr_bal_record = CurrentBalance()# Create new record When registering students
            curr_bal_record.student=self.student
            curr_bal_record.current_balance=self.arrears
            curr_bal_record.save()
        super(FinancialAccount, self).save(*args, **kwargs)


class CurrentBalance(models.Model):
    """Contains current balance statements/records"""
    """For internal use: allows easier reading of students' fees arrears"""
    """This keeps a one to one record of the current balance per child every payment made updates the one record per student """
    student = models.OneToOneField(Student, on_delete=models.CASCADE,unique=True)
    current_balance = models.DecimalField(max_digits=8, decimal_places=2)

administrator/views.py
from pyexpat.errors import messages
from unicodedata import numeric
from urllib.request import proxy_bypass
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from requests import delete
from . import forms
from user_account.models import CustomUser
from student.models import Student
from financial_account.models import FinancialAccount
from info.models import FeesStructure
from django.contrib.auth.models import BaseUserManager
import datetime 
from datetime import datetime,timedelta
from info.models import AcademicCalendar
import pytz
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import io
from django.http import FileResponse
from financial_account.models import CurrentBalance
import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders
from .utils import render_to_pdf

@login_required
def admin_dashboard(request):
    """This view lands the user on  the administration dashboard"""
    """Displaying a list of functionalities afforded the administrator """
    number_of_students = Student.objects.all().count()
    records = CurrentBalance.objects.filter(current_balance__lt = 0).count()
    lunch_subscribers = Student.objects.filter(hot_lunch=True).count()
    transport_subscribers = Student.objects.filter(transport=True).count()
    context ={
        'number_of_students':number_of_students,
        'records':records ,# Studentts with fees arrears
        'lunch_subscribers':lunch_subscribers,
        'transport_subscribers':transport_subscribers
    }
    return render(request,'administrator/admin_dashboard.html', {'context':context})

def date_range(start,end):
    """This view returns a list of datetime instances  of days between 'start' day and 'end' day """
    """It is used in get_term() to retrieve the term number """
    delta = end-start
    days = [start + timedelta(days=i) for i in range(delta.days+1)]
    return days

def get_term(date):
    """This method returns the term number (int) given the date """
    """Uses date_range() to retrieve the list of days in a term"""
    calendar = AcademicCalendar.objects.get(year=date.year)#This is the date provided from user.date_joined, during student registration
    term_1_start_date = calendar.term_1_start_date
    term_1_end_date = calendar.term_1_end_date
    term_2_start_date =calendar.term_2_start_date
    term_2_end_date = calendar.term_2_end_date
    term_3_start_date = calendar.term_3_start_date
    term_3_end_date = calendar.term_3_end_date

    term_1_days = date_range(term_1_start_date,term_1_end_date)
    term_2_days = date_range(term_2_start_date,term_2_end_date)
    term_3_days = date_range(term_3_start_date,term_3_end_date)

    if date in term_1_days:
        return 1
    if date in term_2_days:
        return 2
    if date in term_3_days:
        return 3

def get_term_amount(date,grade,lunch,transport):#Lunch and transport are optionals 
    """This function retrieves the fees due for a given term, provided the current date"""
    """it returns the amount due for a given term ther amount will be negative to indicate amout is due"""
    """This method is used only during student registration, a separate function get_term_amount_continous() calculates the amount for continuing students """
    #date is a datetime instance
    year = date.year#This is the date provided from user.date_joined, during student registration
    term = get_term(date)
    fee = FeesStructure.objects.get(year=2022,term=term,grade=grade)
    amount = fee.admission + fee.diary_and_report_book + fee.tuition_fee # the amount is the core_amount-'not optionals'
    if lunch and not transport:
        amount  = amount+ fee.hot_lunch
    if transport and not lunch:
        amount = amount + fee.transport
    if transport and lunch :
        amount = amount + fee.transport + fee.hot_lunch
    
    return -abs(amount)
@login_required
def register_student(request):
    """This function registers a user, and associates that user to a student which is then associated with a financial account"""
    if request.method == 'GET':
        form = forms.StudentRegistrationForm()
        return render(request,'administrator/student_registration_page.html',{'form':form})
    if request.method =='POST':
        form = forms.StudentRegistrationForm(request.POST,request.FILES)# request.Files to retrieve the image file
        if form.is_valid():
            #Student registration logic
            # 1.create a user
            user = CustomUser()
            user.first_name = form.cleaned_data['first_name']
            user.middle_name = form.cleaned_data['middle_name']
            user.last_name = form.cleaned_data['last_name']
            password = CustomUser.objects.make_random_password()
            user.set_password(password)
            user.is_superuser = False
            user.username = form.cleaned_data['email']
            user.email = form.cleaned_data['email']
            user.is_staff = False
            user.is_active = True
            user.date_of_birth = form.cleaned_data['date_of_birth']
            user.gender = form.cleaned_data['gender']
            
            user.is_administrator = False
            user.is_teacher = False
            user.is_student = True
            #save user
            user.save()

            # 2. Create the student
            student = Student()
            student.grade_admitted_to = form.cleaned_data['grade_admitted_to']
            student.current_grade = form.cleaned_data['grade_admitted_to']
            student.primary_contact_name = form.cleaned_data['primary_contact_name']
            student.primary_contact_phone_number = form.cleaned_data['primary_contact_phone_number']
            student.secondary_contact_name = form.cleaned_data['secondary_contact_name']
            student.secondary_contact_phone_number = form.cleaned_data['secondary_contact_phone_number']
            student.user = user
            #optionals
            student.hot_lunch = form.cleaned_data['hot_lunch']
            student.transport = form.cleaned_data['transport']
            student.save()

            # 3. Create the financial account
                    # - We need to know which term and year we are now given the date
                    # - calculate the core fees items without optioinals, if we have optionals, add them
                    # - create a financial account and Credit that amount to the student financial account
            transaction = FinancialAccount()
            transaction.student = student

            #optionals
            lunch = form.cleaned_data['hot_lunch']
            transport = form.cleaned_data['transport']

            year = user.date_joined.year
            month = user.date_joined.month
            day = user.date_joined.day
            date = datetime(year,month,day)

            #Making the datetime 'timezone aware', so that it can be used by get_term()
            date = date.replace(tzinfo=pytz.UTC)
            
            #Crediting the student the term's fees "+(-amount)"
            transaction.amount = get_term_amount(date,student.grade_admitted_to,lunch,transport)
            transaction.arrears = get_term_amount(date,student.grade_admitted_to,lunch,transport)
            transaction.transaction_type = 'credit'
            transaction.save()
            messages.add_message(request,messages.SUCCESS,"Student Registered Successfully")
            return HttpResponseRedirect(reverse('student_profile', args=[student.user.id]))
        else:
            return render(request,'administrator/student_registration_page.html',{'form':form})
@login_required
def student_profile(request,id):
    """this function displays the student's information including financial history"""
    """Gives access to  update, delete and downloading and printing of financial documents"""
    student = Student.objects.get(pk=id)
    return render(request, 'administrator/student_profile_page.html',{'student':student})
@login_required
def search_student(request):
    """Searches for a given student given the first name and grade """
    if request.method == 'GET':
        form = forms.SearchStudentForm()
        return render(request, 'administrator/search_student_page.html',{'form':form})
    if request.method == 'POST':
        form = forms.SearchStudentForm(request.POST)
        
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            
            grade = form.cleaned_data['grade']

            #this feature allows for getting all the students from a certain grade
            if grade and not first_name :
                students = Student.objects.filter(current_grade=grade)
                return render(request, 'administrator/search_student_page.html',{'students':students,'form':form})
            if grade and first_name:
                students = Student.objects.filter(current_grade=grade).filter(user__first_name__iexact = first_name)
                return render(request, 'administrator/search_student_page.html',{'students':students,'form':form})
            
        else:
            return render(request, 'administrator/search_student_page.html',{'form':form})
@login_required       
def update_student(request,id):
    """Updates student details """
    student = Student.objects.get(pk=id)
    user = CustomUser.objects.get(pk=student.user.id)
    if request.method == 'GET':
        data = {
            'first_name' : user.first_name,
            'middle_name' : user.middle_name,
            'last_name' : user.last_name, 
            'gender' : user.gender,
            'email' : user.email,
            'date_of_birth' : user.date_of_birth,
            'grade_admitted_to' :  student.grade_admitted_to,

administrator/templates/administrator/admin_base.html
{% extends 'base.html' %}
{% load static %}

{%block sidebar%}
<div class="w3-sidebar w3-bar-block w3-light-gray w3-border w3-top " style="width:25%">
    <div class="w3-display-container">
      <div class="display-middle">
        <a href="{% url 'administrator_dashboard'%}"><img src="{% static 'user_account/logo.png'%}" alt="Logo" class="w3-image w3-round" style="width:350px;height:250px;"></a>
      </div>
    </div>
    <a href="{% url 'register_student'%}" class="w3-bar-item w3-button w3-border-bottom">Register Student</a>
    <a href="{% url 'search_student'%}" class="w3-bar-item w3-button w3-border-bottom">Search Student</a>
    <a href="{% url 'reports'%}" class="w3-bar-item w3-button w3-border-bottom">Reports</a>
    <a href="{% url 'search_fees_structure'%}" class="w3-bar-item w3-button w3-border-bottom">Fees Structure</a>
    <br>
    <a href="{% url 'logout'%}" class="w3-bar-item w3-button w3-border-bottom w3-red">Logout</a>
  </div>
{%endblock sidebar%}

{% block body %}

{% endblock body %}

administrator/templates/administrator/admin_dashboard.html
{% extends 'administrator/admin_base.html' %}
{% block body %}
    <div class="w3-container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }} w3-panel w3-green w3-border w3-round"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <h1 >Administrator Dashboard</h1>
        <hr>
        <div class="w3-container  w3-round">
        
                    <div class="w3-card w3-indigo">
                        <p>
                            Number of Students: {{context.number_of_students}}
                        </p>
                    </div>
                    <br>
                    <div class="w3-card w3-indigo">
                        <p>
                            Number of Students with Fees Arrears: {{context.records }}
                        </p>
                    </div>
                    <br>
                    <div class="w3-card w3-indigo">
                        <p>
                            Number of Students Taking Lunch: {{context.lunch_subscribers}}
                        </p>
                    </div>
                    <br>
                    <div class="w3-card w3-indigo">
                        <p>
                            Number of Students taking transport: {{context.transport_subscribers}}
                        </p>
                    </div>

        </div>
        </div>
{% endblock body %}

administrator/templates/administrator/fees_arrears_report.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Fees Arrears Report</title>
  <style>
    #arrears_report {
      
      border-collapse: collapse;
      width: 100%;
    }
    
    #arrears_report td, #arrears_report th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #arrears_report tr:nth-child(even){background-color: #f2f2f2;}
    
    #arrears_report tr:hover {background-color: #ddd;}
    
    #arrears_report th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #04AA6D;
      color: white;
    }
    </style>
</head>
<body>
  <h1>Fees Arrears Report</h1>
  <table id="arrears_report">
    <tr>
      <th>Name</th>
      <th>Grade</th>
      <th>Amount</th>
    </tr>
    {% for record in records %}
      <tr>
        <td> {{record.student.user.first_name}} {{record.student.user.middle_name}} {{record.student.user.last_name}} </td>
        <td>{{record.student.current_grade}}</td>
        <td>{{record.current_balance}}</td>
      </tr>
    {% endfor %}
</table>
</body>
</html>

administrator/templates/administrator/fees_structure_update_page.html
{% extends 'administrator/admin_base.html' %}

{% block body %}
<div class="w3-container">
    <form action="" method="post" class="w3-container w3-border w3-round w3-light-grey">
        <h2>Fees Structure Update Form</h2>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update"  class="w3-button w3-blue w3-round">
        <br>
        <br>
    </form>
    <br>
    <br>
</div>
{% endblock body %}

administrator/templates/administrator/lunch_report.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lunch Report</title>
  <style>
    #lunch_report {
      
      border-collapse: collapse;
      width: 100%;
    }
    
    #lunch_report td, #lunch_report th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #lunch_report tr:nth-child(even){background-color: #f2f2f2;}
    
    #lunch_report tr:hover {background-color: #ddd;}
    
    #lunch_report th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #04AA6D;
      color: white;
    }
    </style>
</head>
<body>
  <table id="lunch_report">
    <tr>
      <th>Name</th>
      <th>Grade</th>
    </tr>
    {% for student in students %}
      <tr>
        <td> {{student.user.first_name}} {{student.user.middle_name}} {{student.user.last_name}} </td>
        <td>{{student.current_grade}}</td>
      </tr>
    {% endfor %}
</table>
</body>
</html>

administrator/templates/administrator/make_payment_page.html
{% extends 'base.html' %}

{% block body   %}
<div class="w3-container">
    <form action="{% url 'make_payment' student.user.id%}" method="post" class="w3-container w3-display-middle w3-light-grey w3-border">
        <h2>Payment Form</h2>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Go" class="w3-button w3-blue w3-round">
        <br>
        <br>
    </form>
</div>
{% endblock body %}

administrator/templates/administrator/search_fees_structure_page.html
{% extends 'administrator/admin_base.html' %}
{% block body %}
    <div class="w3-container">
        <form action="{% url 'search_fees_structure' %}" method="post" class="w3-container w3-border w3-round w3-light-grey">
            <h2>Fees Structure Search Form</h2>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Search" class="w3-button w3-blue w3-round">
            <br>
            <br>
        </form>
        <br>
        <hr>
        {% if fees_struc %}
            <table class="w3-table-all">
                <tr>
                    <th>Year</th>
                    <th>Term</th>
                    <th>Grade</th>
                    <th>Admission</th>
                    <th>Diary and Report Book</th>
                    <th>Tuition Fee</th>
                    <th>Hot Lunch</th>
                    <th>Transport</th>
                    <th>Update</th>
                </tr>
                <tr>
                    <td>{{ fees_struc.year }}</td>
                    <td>{{ fees_struc.term }}</td>
                    <td>{{ fees_struc.grade }}</td>
                    <td>{{ fees_struc.admission }}</td>
                    <td>{{ fees_struc.diary_and_report_book }}</td>
                    <td>{{ fees_struc.tuition_fee }}</td>
                    <td>{{ fees_struc.hot_lunch }}</td>
                    <td>{{ fees_struc.transport }}</td>
                    <td>
                        <a href="{% url 'update_fees_structure' fees_struc.id %}" class="w3-button w3-blue w3-round w3-small">Update</a>
                    </td>
                </tr>
            </table>
        {% endif %}
    </div>
{% endblock body %}

administrator/templates/administrator/search_student_page.html
{% extends 'administrator/admin_base.html' %}

{% block body %}
<div class="w3-container">
    <form action="{% url 'search_student'%}" method="post" class="w3-container w3-border w3-round w3-light-grey">
        <h2>Search Student Form </h2>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Search" class="w3-button w3-blue w3-round">
        <br>
        <br>

    </form>
    <br>
    <hr>
    
    {%if students%}
    <ul class="w3-ul w3-border">
        {% for student in students %}
        <li>
            <a href="{% url 'student_profile' student.user.id %}">{{student.user.first_name}} {{student.user.middle_name}} {{student.user.last_name}}</a>
        </li>
        {%empty%}
        <p>No student exists with that first name </p>
        {% endfor %}
    </ul>
    {%endif%}
</div>
{% endblock %}

administrator/templates/administrator/student_profile_page.html
{% extends 'administrator/admin_base.html' %}
{% load static %}
{% block body %}
    <div class="w3-container">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }} w3-panel w3-green w3-border w3-round"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

          <table class="w3-table-all">
            <tr><h2>Student Info</h2></tr>
            <tr>
              <th>Name:</th>
              <td>{{ student.user.first_name }} {{ student.user.middle_name }} {{ student.user.last_name }}</td>
            </tr>
            <tr>
              <th>Gender:</th>
              <td>{{ student.user.gender }}</td>
            </tr>
            <tr>
              <th>Email:</th>
              <td>{{ student.user.email }}</td>
            </tr>
            <tr>
              <th>Primary Contact Name:</th>
              <td>{{ student.primary_contact_name }}</td>
            </tr>
            <tr>
              <th>rimary Contact Phone Number:</th>
              <td>{{ student.primary_contact_phone_number }}</td>
            </tr>
            <tr>
              <th>Secondary Contact Name:</th>
              <td>{{ student.secondary_contact_name }}</td>
            </tr>
            <tr>
              <th>Secondary Contact Phone Number:</th>
              <td>{{ student.secondary_contact_phone_number }}</td>
            </tr>
            <tr>
              <th>Hot Lunch:</th>
              <td>{{ student.hot_lunch }}</td>
            </tr>
            <tr>
              <th>Transport:</th>
              <td>{{ student.transport }}</td>
            </tr>
          </table>
        <br>
        <a href="{% url 'update_student' student.user.id %}" class="w3-button w3-blue w3-round">Update Student Details</a>
        <br>
        <br>
        <a href=" {% url 'delete_student' student.user.id %} " class="w3-button w3-red w3-round">Delete Student</a>
        <br>
        <hr>
        <h1>Transaction History</h1>
        <table class="w3-table-all">
            <tr>
                <th>Transaction ID</th>
                <th>Transaction Type</th>
                <th>Date of Payment</th>
                <th>Amount Payed</th>
                <th>Arrears</th>
                <th>Details</th>
            </tr>
            {% for transaction in student.financialaccount_set.all %}
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td>{{ transaction.transaction_type }}</td>
                    <td>{{ transaction.date_of_payment }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.arrears }}</td>
                    <td>
                        <a href=" {% url 'download_receipt' transaction.id %} " class="w3-button w3-small w3-blue w3-round">Details</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <br>
        <a href=" {% url 'download_statement' student.user.id %}" class="w3-button w3-blue w3-round">Download Statement</a>
  
        <a href=" {% url 'make_payment' student.user.id %}" class="w3-button w3-blue w3-round">Make Payment</a>
        <br>
        <br>
    </div>
{% endblock body %}

administrator/templates/administrator/student_registration_page.html
{% extends 'administrator/admin_base.html' %}

{% block body %}
<div class="w3-container">
    <form action="" method="post" enctypt="multipart/form-data" class="w3-container w3-border w3-round w3-light-grey">
        <h2>Student Registration Form</h2>
        {% csrf_token %}
        {{form.non_field_errors}}
        
        {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
        <input type="submit" value="Register" class="w3-button w3-blue w3-round">
        <br>
        <br>
    </form>
    <br>
</div>
{% endblock body %}

administrator/templates/administrator/student_update_page.html
{% extends 'administrator/admin_base.html' %}

{% block body %}

<div class="w3-container">
    <form action="" method="post" enctypt="multipart/form-data" class="w3-container w3-border w3-round w3-light-grey">
        <h2>Student Update Page</h2>
        {% csrf_token %}
        {{form.non_field_errors}}
        
        {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
            {% if field.help_text %}
            <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
        </div>
    {% endfor %}
        <input type="submit" value="Update" class="w3-button w3-blue w3-round">
        <br>
        <br>
    </form>
    <br>
    <br>
</div>
{% endblock body %}

administrator/templates/administrator/transaction_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'w3.css'%}">
  <title>Fees Payment Detail</title>
  <style>
    #payment_details {
      
      border-collapse: collapse;
      width: 100%;
    }
    
    #payment_details td, #payment_details th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #payment_details tr:nth-child(even){background-color: #f2f2f2;}
    
    #payment_details tr:hover {background-color: #ddd;}
    
    #payment_details th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #04AA6D;
      color: white;
    }
    </style>
</head>
<body>
  <h2>Fees Payment Details</h2>
  {% if transaction %}
<table id="payment_details">
    <tr>
      
      <th>Transaction ID</th>
      <th>Transaction Type</th>
      <th>Date of Payment</th>
      <th>Amount Payed</th>
      <th>Arrears</th>
    </tr>
      <tr>
        <td> {{transaction.id}} </td>
        <td>{{transaction.transaction_type}}</td>
        <td>{{transaction.date_of_payment}}</td>
        <td>{{transaction.amount}}</td>
        <td> {{transaction.arrears}} </td>
      </tr>
  </table>
{% endif %}
</body>
</html>

administrator/templates/administrator/transport_report.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transport Report</title>
  <style>
    #transport_report {
      
      border-collapse: collapse;
      width: 100%;
    }
    
    #transport_report td, #transport_report th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #transport_report tr:nth-child(even){background-color: #f2f2f2;}
    
    #transport_report tr:hover {background-color: #ddd;}
    
    #transport_report th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #04AA6D;
      color: white;
    }
    </style>
</head>
<body>
  <table id="transport_report">
    <tr>
      <th>Name</th>
      <th>Grade</th>
    </tr>
    {% for student in students %}
      <tr>
        <td> {{student.user.first_name}} {{student.user.middle_name}} {{student.user.last_name}} </td>
        <td>{{student.current_grade}}</td>
      </tr>
    {% endfor %}
</table>
</body>
</html>

administrator/templates/administrator/user_printer.html
{% extends 'administrator/admin_base.html' %}

{% block body %}
Good Work {{name}}
{{myvar}}
{% endblock body %}